"""Dodato polje user_role u User model

Revision ID: 1d26a15db48d
Revises: 2f3220bcf712
Create Date: 2025-09-27 14:51:39.479960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d26a15db48d'
down_revision = '2f3220bcf712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=255), nullable=False))
    
    # Postavljanje vrednosti za postojeće korisnike
    from sqlalchemy import text
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer
    
    user_table = table('user',
        column('id', Integer),
        column('user_role', String)
    )
    
    # Postavi admin za id=0
    op.execute(
        user_table.update().where(user_table.c.id == 0).values(user_role='admin')
    )
    
    # Postavi user za sve ostale korisnike
    op.execute(
        user_table.update().where(user_table.c.id > 0).values(user_role='user')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
