"""Add fund transfer functionality

Revision ID: 2f3220bcf712
Revises: d3fa5e4b6881
Create Date: 2025-09-22 16:14:36.372648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3220bcf712'
down_revision = 'd3fa5e4b6881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_transfer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fund_transfer', ['fund_transfer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fund_transfer_id')

    # ### end Alembic commands ###
