"""dodato school_email u School

Revision ID: 355394eafce7
Revises: a802bf332116
Create Date: 2025-05-20 15:50:02.428462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355394eafce7'
down_revision = 'a802bf332116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_email', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('school_email')

    # ### end Alembic commands ###
