"""Dodaj payee_name polje u SupplierTransaction

Revision ID: 6c37334d72f5
Revises: d631ecc28bed
Create Date: 2025-12-06 22:15:42.022934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c37334d72f5'
down_revision = 'd631ecc28bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payee_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_transaction', schema=None) as batch_op:
        batch_op.drop_column('payee_name')

    # ### end Alembic commands ###
