"""Add SMTP error logging table

Revision ID: 6fac3194bb61
Revises: a3fc8c9c51da
Create Date: 2025-12-08 21:04:01.235502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fac3194bb61'
down_revision = 'a3fc8c9c51da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['transaction_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smtp_error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smtp_error_logs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_smtp_error_logs_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_smtp_error_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp_error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtp_error_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_smtp_error_logs_resolved'))
        batch_op.drop_index(batch_op.f('ix_smtp_error_logs_error_type'))

    op.drop_table('smtp_error_logs')
    # ### end Alembic commands ###
