"""Dodaj sending_email polje u School model

Revision ID: a3fc8c9c51da
Revises: 6c37334d72f5
Create Date: 2025-12-07 12:07:35.997184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fc8c9c51da'
down_revision = '6c37334d72f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sending_email', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('sending_email')

    # ### end Alembic commands ###
