"""inicijalna migracija

Revision ID: a802bf332116
Revises: 
Create Date: 2025-05-20 15:07:16.049931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a802bf332116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Isključujemo foreign key provere
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.alter_column('school_bank_accounts',
               existing_type=mysql.JSON(),
               nullable=False)
        batch_op.alter_column('class_plus_one',
               existing_type=sa.DATE(),
               nullable=False)
        # batch_op.drop_column('school_bank_account')

    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('reference_number_spiri',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('service_item_class',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=250),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('student_payment', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.alter_column('student_debt_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_payment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'school', ['school_id'], ['id'])

    # ### end Alembic commands ###
    
    # Ponovo uključujemo foreign key provere
    op.execute('SET FOREIGN_KEY_CHECKS=1;')


def downgrade():
    # Isključujemo foreign key provere
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.alter_column('student_payment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_debt_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student_payment', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('service_item_class',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=True)
        batch_op.alter_column('reference_number_spiri',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('school', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('school_bank_account', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.alter_column('class_plus_one',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('school_bank_accounts',
               existing_type=mysql.JSON(),
               nullable=True)

    # ### end Alembic commands ###
    
    # Ponovo uključujemo foreign key provere
    op.execute('SET FOREIGN_KEY_CHECKS=1;')
