"""Dodaj supplier_billing_options polje u School model

Revision ID: b1645b52ff5c
Revises: abc123def456
Create Date: 2025-11-20 16:24:51.710605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1645b52ff5c'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_billing_options', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('supplier_billing_options')

    # ### end Alembic commands ###
