"""ServiceItem.service_item_class promenjen u string(255)

Revision ID: caa5c1f74437
Revises: e815aaefe61c
Create Date: 2025-05-22 15:36:30.183811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caa5c1f74437'
down_revision = 'e815aaefe61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.alter_column('service_item_class',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.alter_column('service_item_class',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
