"""Dodato broj_razreda i broj_odeljenja u School model

Revision ID: cb6aac389e14
Revises: f7e068a8c7c6
Create Date: 2025-10-16 21:55:23.173116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6aac389e14'
down_revision = 'f7e068a8c7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broj_razreda', sa.Integer(), nullable=False, server_default='8'))
        batch_op.add_column(sa.Column('broj_odeljenja', sa.Integer(), nullable=False, server_default='15'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('broj_odeljenja')
        batch_op.drop_column('broj_razreda')

    # ### end Alembic commands ###
