"""dodata kolona debt_sent u TransactionRecords

Revision ID: d3fa5e4b6881
Revises: caa5c1f74437
Create Date: 2025-06-26 21:01:33.644811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fa5e4b6881'
down_revision = 'caa5c1f74437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.drop_column('debt_sent')

    # ### end Alembic commands ###
