"""Dodaj SupplierPayment tabelu i promeni SupplierTransaction FK

Revision ID: d631ecc28bed
Revises: 8501d412bc47
Create Date: 2025-12-06 21:46:35.171188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd631ecc28bed'
down_revision = '8501d412bc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('bank_account', sa.String(length=255), nullable=False),
    sa.Column('statment_nubmer', sa.Integer(), nullable=False),
    sa.Column('total_payment_amount', sa.Float(), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=False),
    sa.Column('number_of_errors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_payment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('supplier_transaction_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'supplier_payment', ['supplier_payment_id'], ['id'])
        batch_op.drop_column('student_payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_payment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('supplier_transaction_ibfk_1', 'student_payment', ['student_payment_id'], ['id'])
        batch_op.drop_column('supplier_payment_id')

    op.drop_table('supplier_payment')
    # ### end Alembic commands ###
