"""izmenjeno kod student_debt_id i student_payment_id da može da sačuva None

Revision ID: e815aaefe61c
Revises: 355394eafce7
Create Date: 2025-05-21 16:02:03.076417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e815aaefe61c'
down_revision = '355394eafce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.alter_column('student_debt_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_payment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.alter_column('student_payment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_debt_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
