"""Dodata funkcionalnos rasknjižavanja

Revision ID: f7e068a8c7c6
Revises: 1d26a15db48d
Create Date: 2025-10-04 09:34:43.941120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e068a8c7c6'
down_revision = '1d26a15db48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_writeoff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'debt_write_off', ['debt_writeoff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('debt_writeoff_id')

    # ### end Alembic commands ###
